-- Karbi Anglong Autonomous Council Seed Records

-- 1. Departments
INSERT INTO departments (id, code, name, hod_name, contact_email, phone, description) VALUES
                                                                                          (1, 'GAD', 'General Administration Department', 'Mukesh Chandra Sahu, IAS', 'gad.kaac@assam.gov.in', '+91 3671 272221', 'Central Council administration and executive governance'),
                                                                                          (2, 'REV', 'Revenue & Land Reforms Department', 'Sarkhe Terang, ACS', 'revenue.kaac@assam.gov.in', '+91 3671 272230', 'Land settlement, allotment, and revenue assessment'),
                                                                                          (3, 'PWD', 'Public Works Department (Roads & Building)', 'Er. Rajesh Tokbi', 'pwd.kaac@assam.gov.in', '+91 3671 272314', 'Council infrastructure and arterial road networks');

-- 2. Users (IDs 1 through 7 defined so foreign keys match)
INSERT INTO users (id, username, password, full_name, email, phone, designation, role, department_id, status) VALUES
                                                                                                                  (1, 'admin', '$2a$10$DxXomqyiwps0HP6b03tzDep2a3M65Qi9GlnzZBMeYjMYG144sn1N.', 'Monjir Tissopi', 'monjir.tissopi@kaac.gov.in', '+91 9435011001', 'Secretary to Karbi Anglong Autonomous Council', 'ADMIN', 1, 'ACTIVE'),
                                                                                                                  (2, 'cem_tuliram', '$2a$10$DxXomqyiwps0HP6b03tzDep2a3M65Qi9GlnzZBMeYjMYG144sn1N.', 'Hon. Tuliram Ronghang', 'cem@kaac.gov.in', '+91 9435011002', 'Chief Executive Member (CEM)', 'CHAIRPERSON', 1, 'ACTIVE'),
                                                                                                                  (3, 'staff_talo', '$2a$10$DxXomqyiwps0HP6b03tzDep2a3M65Qi9GlnzZBMeYjMYG144sn1N.', 'Talo Tisso', 'talo.tisso@kaac.gov.in', '+91 9435033001', 'Meeting Coordinator / Protocol Officer', 'STAFF', 1, 'ACTIVE'),
                                                                                                                  (7, 'staff_demi', '$2a$10$DxXomqyiwps0HP6b03tzDep2a3M65Qi9GlnzZBMeYjMYG144sn1N.', 'Demi Jigdung', 'demi.jigdung@kaac.gov.in', '+91 9435033001', 'Meeting Coordinator / Protocol Officer', 'STAFF', 1, 'ACTIVE'),
                                                                                                                  (4, 'staff_dirti', '$2a$10$DxXomqyiwps0HP6b03tzDep2a3M65Qi9GlnzZBMeYjMYG144sn1N.', 'Raikom Ingtipi', 'raikom.terang@kaac.gov.in', '+91 9435033004', 'Meeting Coordinator / Protocol Officer', 'STAFF', 2, 'ACTIVE'),
                                                                                                                  (5, 'staff_raikom', '$2a$10$DxXomqyiwps0HP6b03tzDep2a3M65Qi9GlnzZBMeYjMYG144sn1N.', 'Dirti Ingtipi', 'dirti.ingtipi@kaac.gov.in', '+91 9435033004', 'Meeting Coordinator / Protocol Officer', 'STAFF', 2, 'ACTIVE'),
                                                                                                                  (6, 'staff_sangita', '$2a$10$DxXomqyiwps0HP6b03tzDep2a3M65Qi9GlnzZBMeYjMYG144sn1N.', 'Sangita Phonglosa', 'sangita.phonglosa@kaac.gov.in', '+91 9435033008', 'Meeting Coordinator / Protocol Officer', 'STAFF', 3, 'ACTIVE');

-- 3. Meeting Rooms
INSERT INTO meeting_rooms (id, room_number, name, location, capacity, facilities, status, description) VALUES
                                                                                                           (1, 'KAAC-H1', 'Council Central Session Hall', 'Main Secretariat Complex, Ground Floor, Diphu', 120, 'Digital Audio System, 4K Projectors', 'AVAILABLE', 'Primary legislative hall.'),
                                                                                                           (2, 'KAAC-H2', 'CEM Executive Conference Room', 'CEM Secretariat Wing, 1st Floor, Diphu', 35, 'Cisco Video Conference, Smart Board', 'AVAILABLE', 'Executive council chamber.'),
                                                                                                           (3, 'KAAC-CR1', 'Meeting Room', 'New Building 2nd Floor, Diphu', 25, 'Projector, WiFi, AC', 'AVAILABLE', 'Committee review room.');

-- 4. Meeting Schedules
-- INSERT INTO meeting_schedules (title, agenda, meeting_date, start_time, end_time, department_id, meeting_room_id, chairperson_id, assigned_staff_id, created_by_user_id, status, priority, meeting_type, virtual_link, attendees, minutes_of_meeting) VALUES
--                                                                                                                                                                                                                                                           ('KAAC Annual Executive Council Budget Review & Strategy Meeting', '1. Annual budget allocations.\n2. Fund sanction.', '2026-08-28', '10:00', '12:30', 1, 1, 2, 5, 5, 'SCHEDULED', 'HIGH', 'PHYSICAL', '', 'Hon. CEM, Secretary KAAC', NULL),
--                                                                                                                                                                                                                                                           ('Rural Connectivity & Hill Roads Infrastructure Progress Review', '1. Scrutiny of arterial highway projects.', '2026-08-28', '14:00', '16:30', 3, 3, 3, 5, 5, 'SCHEDULED', 'HIGH', 'PHYSICAL', '', 'Hon. EM PWD, Chief Engineer', NULL),
--                                                                                                                                                                                                                                                           ('Morning Secretariat Standing Committee Coordination Briefing', '1. Standing committee coordination.', '2026-08-28', '08:30', '09:30', 1, 1, 4, 6, 6, 'COMPLETED', 'NORMAL', 'VIRTUAL', 'https://meet.google.com/kaac-edu-rev', 'Hon. EM Education', 'Reviewed high school modernization initiatives.'),
--                                                                                                                                                                                                                                                           ('Executive Council Review on District Infrastructure & PWD Roads', '1. Progress review of rural connectivity.', '2026-09-02', '10:00', '12:30', 3, 2, 2, 7, 7, 'SCHEDULED', 'NORMAL', 'PHYSICAL', '', 'Hon. CEM, EM PWD', NULL),
--                                                                                                                                                                                                                                                           ('Inter-Departmental Land Allotment & Settlement Scrutiny', '1. Review of land settlement.', '2026-09-03', '14:00', '16:30', 2, 3, 3, 5, 5, 'SCHEDULED', 'NORMAL', 'PHYSICAL', '', 'Hon. EM Revenue', NULL);