-- Karbi Anglong Autonomous Council (KAAC) H2 Database Schema DDL
-- Database: jdbc:h2:mem:kaac_meetings_db

CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    hod_name VARCHAR(120),
    contact_email VARCHAR(100),
    phone VARCHAR(30),
    description VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(20),
    designation VARCHAR(100),
    role VARCHAR(20) NOT NULL, -- ADMIN, STAFF, CHAIRPERSON
    department_id BIGINT,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_dept FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS meeting_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    location VARCHAR(200) NOT NULL,
    capacity INT NOT NULL,
    facilities VARCHAR(300),
    status VARCHAR(30) DEFAULT 'AVAILABLE',
    description VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS meeting_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    agenda CLOB,
    meeting_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    department_id BIGINT NOT NULL,
    meeting_room_id BIGINT NOT NULL,
    chairperson_id BIGINT NOT NULL, -- MANDATORY: Role must be CHAIRPERSON
    assigned_staff_id BIGINT NOT NULL, -- MANDATORY: Staff member handling the meeting
    created_by_user_id BIGINT NOT NULL,
    status VARCHAR(30) DEFAULT 'SCHEDULED',
    priority VARCHAR(20) DEFAULT 'NORMAL',
    meeting_type VARCHAR(20) DEFAULT 'PHYSICAL',
    virtual_link VARCHAR(255),
    attendees CLOB,
    minutes_of_meeting CLOB,
    decision_notes CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sched_dept FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_sched_room FOREIGN KEY (meeting_room_id) REFERENCES meeting_rooms(id),
    CONSTRAINT fk_sched_chair FOREIGN KEY (chairperson_id) REFERENCES users(id),
    CONSTRAINT fk_sched_staff FOREIGN KEY (assigned_staff_id) REFERENCES users(id),
    CONSTRAINT fk_sched_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id)
);
